#!/bin/bash

echo "Hello from check program!" >&2

set -e

PAYLOAD="$(cat <&0)"
BRANCH=$(jq -r '.branch // "main"' <<< $PAYLOAD)
REPO=$(jq -r '.repository // ""' <<< $PAYLOAD)
PREV=$(jq -r '.version.ref // ""' <<< $PAYLOAD)

TOKEN=$(bash getToken.sh <<< PAYLOAD)
LATEST=$(curl -s -X GET -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" https://api.github.com/repos/$ACCOUNT/$REPO/branches \
       | jq -r --arg branch $BRANCH 'map(select(.name==$branch)) | .[0].commit.sha')

if [ $PREV != $LATEST ]; then
	jq -n --arg value $LATEST '[{"ref": $value}]'
else
	jq -n '[]'
fi

