#!/bin/bash
set -ex
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD="$(cat <&0)"
BRANCH=$(jq -r '.source.branch // "main"' <<< $PAYLOAD)
ACCOUNT=$(jq -r '.source.account // ""' <<< $PAYLOAD)
REPO=$(jq -r '.source.repository // ""' <<< $PAYLOAD)
PREV=$(jq -r '.version.ref // ""' <<< $PAYLOAD)

TOKEN=$(bash $(dirname $0)/getToken.sh <<< $PAYLOAD)
LATEST=$(curl -s -X GET -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" https://api.github.com/repos/$ACCOUNT/$REPO/branches \
       | jq -r --arg branch $BRANCH 'map(select(.name==$branch)) | .[0].commit.sha')

if [ "$PREV" != "$LATEST" ]; then
	jq -n --arg value $LATEST '[{"ref": $value}]' >&3
else
	jq -n '[]' >&3
fi

