#!/bin/bash

set -e

PAYLOAD="$(cat <&0)"
DEST=$1

ACCOUNT=$(jq -r '.account // ""' <<< $PAYLOAD)
REPO=$(jq -r '.repository // ""' <<< $PAYLOAD)
VERSION=$(jq -r '.version.ref // ""' <<< PAYLOAD)
TOKEN=$(bash getToken.sh <<< PAYLOAD)

git clone https://x-access-token:$TOKEN@github.com/$ACCOUNT/$REPO.git $DEST
cd $DEST
git checkout $VERSION

