#!/bin/bash

set -ex
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD="$(cat <&0)"
DEST=$1

ACCOUNT=$(jq -r '.source.account // ""' <<< $PAYLOAD)
REPO=$(jq -r '.source.repository // ""' <<< $PAYLOAD)
VERSION=$(jq -r '.version.ref // ""' <<< $PAYLOAD)
TOKEN=$(bash $(dirname $0)/getToken.sh <<< $PAYLOAD)

git clone https://x-access-token:$TOKEN@github.com/$ACCOUNT/$REPO.git $DEST
cd $DEST
git checkout $VERSION
ls

jq -n --arg version $VERSION '{"version":{"ref": $version}, "metadata": []}' >&3

